nextRouting:
  component: "./node_modules/@sls-next/serverless-component"
  inputs:
    name:
      defaultLambda: DefaultLambda #Default Lambda의 이름 설정
      imageLambda: ImageLambda # Image Lambda의 이름 설정
    bucketRegion: "ap-southeast-2" # S3 Bucket 지역 설정
    cloudfront:
      comment: "next routing" # CloudFront 설명 설정
